[book]
authors = ["Karl David Hedgren", "Love Lyckaro"]
language = "en"
multilingual = false
src = "src"
title = "Data101"

[output.html]
default-theme = "Tentaportalen"
# [preprocessor.data101]
# command = "./preprocessor/target/release/preprocessor-data101"
